service: api-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  # Listar médicos e horários disponíveis
  listarMedicos:
    handler: src/agenda/controller/medicos.controller.listarMedicos
    events:
      - http:
          path: agendas
          method: get
          cors: true

  # Criar agendamento
  criarAgendamento:
    handler: src/agendamento/controller/agendamentos.controller.criarAgendamento
    events:
      - http:
          path: agendamento
          method: post
          cors: true

# No additional AWS resources needed since we're using mocked data 