service: api-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  # Listar médicos e horários disponíveis
  getAgendas:
    handler: src/index.getAgendas
    events:
      - http:
          path: agendas
          method: get
          cors: true

  # Listar médicos com filtros
  getMedicos:
    handler: src/index.getMedicos
    events:
      - http:
          path: medicos
          method: get
          cors: true

  # Agendamento endpoints
  getAgendamentos:
    handler: src/index.getAgendamentos
    events:
      - http:
          path: agendamento
          method: get
          cors: true

  getAgendamentoById:
    handler: src/index.getAgendamentoById
    events:
      - http:
          path: agendamento/{id}
          method: get
          cors: true

  createAgendamento:
    handler: src/index.createAgendamento
    events:
      - http:
          path: agendamento
          method: post
          cors: true

  deleteAgendamento:
    handler: src/index.deleteAgendamento
    events:
      - http:
          path: agendamento/{id}
          method: delete
          cors: true

# Restante Mockado 